apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
  annotations:
    x-gitter-trigger-branch: '["refs/heads/main", "refs/heads/dev-*"]'
    x-gitter-enabled: "true"
spec:
  params:
    - name: image_tag
      type: string
    - name: binaries_to_build
      type: string
      default: "PIPRegistry"

  tasks:
    - name: ginger-connector-setup
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: ginger-connector-setup
          - name: namespace
            value: default

    - name: build-amd64-linux
      runAfter:
        - ginger-connector-setup
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-amd64-linux
          - name: namespace
            value: default
      params:
        - name: binaries_to_build
          value: "$(params.binaries_to_build)"

    - name: push-pip-registry-image
      runAfter:
        - build-amd64-linux
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-image
          - name: namespace
            value: default
      params:
        - name: image_tag
          value: "$(params.image_tag)"
        - name: org_id
          value: "$(params.org_id)"
        - name: image_name
          value: "pip-registry"
        - name: binary_name
          value: "PIPRegistry"
        - name: entrypoint
          value: '"/usr/local/bin/PIPRegistry"'
        - name: base_image
          value: "docker.io/gingersociety/rust-rocket-api-runner:latest"
        - name: extra_copy_src
          value: "./Rocket.toml"
        - name: extra_copy_dest
          value: "/Rocket.toml"

    - name: notify-version-update
      runAfter:
        - push-pip-registry-image
      taskSpec:
        steps:
          - name: echo
            image: alpine
            script: |
              #!/bin/sh
              echo "Hello World - all previous tasks are done!"